# Generated by Django 5.2.7 on 2025-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variety',
            name='image',
            field=models.ImageField(upload_to='product_categories'),
        ),
        migrations.AlterField(
            model_name='product_variety',
            name='type',
            field=models.CharField(choices=[('LAFK', 'Learning Apps For Kids'), ('PF', 'Popular Fictions'), ('AAL', 'All About Love'), ('MG', 'Manga Club'), ('NA', 'New Arrivals'), ('MC', 'Marvel Comics'), ('DC', 'DC Comics'), ('RF', 'Romance & Fictions'), ('KB', 'Kids Books'), ('MT', 'Mythology & Tails')], max_length=4),
        ),
    ]
