# Generated by Django 5.2.7 on 2025-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0002_alter_product_variety_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarvelComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marvel_comics/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
